/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'villageId' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Village = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'shortCode' : IDL.Text,
});
export const Loan = IDL.Record({
  'id' : IDL.Nat,
  'emi' : IDL.Nat,
  'status' : IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null }),
  'principal' : IDL.Nat,
  'processingFee' : IDL.Nat,
  'loanId' : IDL.Text,
  'totalInterest' : IDL.Nat,
  'tenureMonths' : IDL.Nat,
  'villageId' : IDL.Nat,
  'interestRate' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Nat,
  'disbursedAt' : IDL.Int,
});
export const BalanceTransaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'type' : IDL.Variant({
    'adjustment' : IDL.Null,
    'collection' : IDL.Null,
    'disbursal' : IDL.Null,
  }),
  'referenceId' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalOutstanding' : IDL.Nat,
  'principalOutstanding' : IDL.Nat,
  'balanceInHand' : IDL.Nat,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'penalty' : IDL.Nat,
  'loanId' : IDL.Text,
  'totalOutstanding' : IDL.Nat,
  'amountPaid' : IDL.Nat,
  'notes' : IDL.Text,
  'paymentDate' : IDL.Int,
  'customerId' : IDL.Nat,
  'receiptNo' : IDL.Text,
  'outstandingPrincipal' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'balanceAdjustment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Principal],
      [Customer],
      [],
    ),
  'createVillage' : IDL.Func([IDL.Text, IDL.Text], [Village], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteVillage' : IDL.Func([IDL.Nat], [], []),
  'disburseLoan' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [Loan],
      [],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(BalanceTransaction)], ['query']),
  'getAllVillages' : IDL.Func([], [IDL.Vec(Village)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLoansByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Loan)], ['query']),
  'getPaymentsByLoan' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVillage' : IDL.Func([IDL.Nat], [Village], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [Payment],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Customer],
      [],
    ),
  'updateVillage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Village], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'villageId' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Village = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'shortCode' : IDL.Text,
  });
  const Loan = IDL.Record({
    'id' : IDL.Nat,
    'emi' : IDL.Nat,
    'status' : IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null }),
    'principal' : IDL.Nat,
    'processingFee' : IDL.Nat,
    'loanId' : IDL.Text,
    'totalInterest' : IDL.Nat,
    'tenureMonths' : IDL.Nat,
    'villageId' : IDL.Nat,
    'interestRate' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Nat,
    'disbursedAt' : IDL.Int,
  });
  const BalanceTransaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'type' : IDL.Variant({
      'adjustment' : IDL.Null,
      'collection' : IDL.Null,
      'disbursal' : IDL.Null,
    }),
    'referenceId' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalOutstanding' : IDL.Nat,
    'principalOutstanding' : IDL.Nat,
    'balanceInHand' : IDL.Nat,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'penalty' : IDL.Nat,
    'loanId' : IDL.Text,
    'totalOutstanding' : IDL.Nat,
    'amountPaid' : IDL.Nat,
    'notes' : IDL.Text,
    'paymentDate' : IDL.Int,
    'customerId' : IDL.Nat,
    'receiptNo' : IDL.Text,
    'outstandingPrincipal' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'balanceAdjustment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Principal],
        [Customer],
        [],
      ),
    'createVillage' : IDL.Func([IDL.Text, IDL.Text], [Village], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteVillage' : IDL.Func([IDL.Nat], [], []),
    'disburseLoan' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [Loan],
        [],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(BalanceTransaction)],
        ['query'],
      ),
    'getAllVillages' : IDL.Func([], [IDL.Vec(Village)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLoansByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Loan)], ['query']),
    'getPaymentsByLoan' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVillage' : IDL.Func([IDL.Nat], [Village], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [Payment],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Customer],
        [],
      ),
    'updateVillage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Village], []),
  });
};

export const init = ({ IDL }) => { return []; };